version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  db_data:
